version: "3.9"

services:
  my-postgres:
    image: postgres:latest
    restart: always
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - ../../../Desktop/pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

networks:
  app-network:
    driver: bridge